services:
  codux-service:
    image: ghcr.io/duxweb/codux-service:latest
    container_name: codux-service
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./data:/data
      - ./deploy/docker.toml:/opt/codux-service/config.toml:ro
    command: ["-config", "/opt/codux-service/config.toml"]
